TankiWiki/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomePageView.as_view(), name="home"),
    path("cannons/", include("sectioncannons.urls")),
    path("hulls/", include("sectionhulls.urls")),
    path("paints/", include("sectionpaints.urls")),
    path("kits/", include("sectionkits.urls")),
    path("ranks/", include("sectionranks.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sectionranks/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.RanksPageView.as_view(), name="ranks-main"),
    path("<str:r>", views.RanksDetailView.as_view(), name="ranks-detail")
]

sectionpaints/models.py
from django.db import models
from sectionranks.models import Rank


class Paint(models.Model):
    name = models.CharField(verbose_name="Название", max_length=20, unique=True)
    slug_name = models.SlugField(max_length=20, blank=True)
    image_icon = models.ImageField(upload_to="Paints", verbose_name="Иконка в гараже")
    image_view = models.ImageField(upload_to="Paints", verbose_name="Вид на танке")
    rank_required = models.ForeignKey(Rank, on_delete=models.DO_NOTHING, verbose_name="Требуемое звание")
    cost = models.IntegerField(verbose_name="Стоимость")
    description = models.TextField(verbose_name="Описание в гараже", null=True, blank=True)

    have_resist = models.BooleanField(verbose_name="Имеет защиту от пушек")
    resist_smoky = models.SmallIntegerField(verbose_name="Зашита от Смоки", null=True, blank=True)
    resist_firebird = models.SmallIntegerField(verbose_name="Зашита от Огнемёта", null=True, blank=True)
    resist_twins = models.SmallIntegerField(verbose_name="Зашита от Твинса", null=True, blank=True)
    resist_hammer = models.SmallIntegerField(verbose_name="Зашита от Молота", null=True, blank=True)
    resist_railgun = models.SmallIntegerField(verbose_name="Зашита от Рельсы", null=True, blank=True)
    resist_isida = models.SmallIntegerField(verbose_name="Зашита от Изиды", null=True, blank=True)
    resist_vulcan = models.SmallIntegerField(verbose_name="Зашита от Вулкана", null=True, blank=True)
    resist_thunder = models.SmallIntegerField(verbose_name="Зашита от Грома", null=True, blank=True)
    resist_freeze = models.SmallIntegerField(verbose_name="Зашита от Фриза", null=True, blank=True)
    resist_ricochet = models.SmallIntegerField(verbose_name="Зашита от Рикошета", null=True, blank=True)
    resist_shaft = models.SmallIntegerField(verbose_name="Зашита от Шафта", null=True, blank=True)
    resist_mines = models.SmallIntegerField(verbose_name="Зашита от мин", null=True, blank=True)
    resist_all = models.SmallIntegerField(verbose_name="Зашита от всех пушек и мин", null=True, blank=True)

    class Meta:
        verbose_name = "Краска"
        verbose_name_plural = "Краски"

    def __str__(self):
        return f"{self.name}"

sectionranks/models.py
from django.db import models


class Rank(models.Model):
    rank_name = models.CharField(max_length=20, verbose_name="Звание", unique=True)
    slug_name = models.SlugField(max_length=20, unique=True, blank=True)
    rank_icon = models.ImageField(upload_to="Ranks", verbose_name="Иконка")
    exp_start = models.IntegerField(verbose_name="Опыт")
    exp_next = models.IntegerField(verbose_name="Опыт до следующего звания")
    cry_bonus = models.IntegerField(verbose_name="Награда")

    class Meta:
        verbose_name = "Звание"
        verbose_name_plural = "Звания"

    def __str__(self):
        return f"{self.rank_name}"

sectionranks/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from sectionranks.models import Rank
from sectionkits.models import ArmamentKit, SupplyKit, TankKit


class RanksPageView(View):
    def get(self, request):

        rank_list = Rank.objects.all()

        data = {"rank_list": rank_list}
        return render(request, "sectionranks/ranks_main.html", context=data)


class RanksDetailView(View):
    @staticmethod
    def get_prev_next_rank(rank):
        result = []

        query1 = Rank.objects.filter(id=rank.id - 1)
        if query1.exists():
            result.append(query1[0])
        else:
            result.append(None)

        query2 = Rank.objects.filter(id=rank.id + 1)
        if query2.exists():
            result.append(query2[0])
        else:
            result.append(None)

        return result

    def get(self, request, r):
        query = Rank.objects.filter(slug_name=r)

        if query.exists():
            rank_detail = query.get(slug_name=r)
            prev_next = self.get_prev_next_rank(rank_detail)
            arm_kits = ArmamentKit.objects.filter(rank_start=rank_detail.id)
            supply_kits = SupplyKit.objects.filter(rank_start=rank_detail.id)
            kits = TankKit.objects.filter(rank_start=rank_detail.id)

            data = {"rank": rank_detail, "prev_rank": prev_next[0], "next_rank": prev_next[1],
                    "arm_kits": arm_kits, "supply_kits": supply_kits, "kits": kits}
            return render(request, "sectionranks/ranks_detail.html", context=data)

        else:
            data = {"rank": r}
            return render(request, "sectionranks/ranks_no_such_rank.html", context=data)

sectionranks/templates/sectionranks/includes_unlocked_cannons.html
{% load static %}
<a class="section-item-2" href="/cannons/{{ item.cannon.slug_name }}">
    <div align="center">
        <h3 class="section-item-name">{{ item.cannon.name }} {{ item.modification }}</h3>
        <br>
        <img src="{{ item.image.url }}">
    </div>
</a>

sectionranks/templates/sectionranks/includes_unlocked_hulls.html
{% load static %}
<a class="section-item-2" href="/hulls/{{ item.hull.slug_name }}">
    <div align="center">
        <h3 class="section-item-name">{{ item.hull.name }} {{ item.modification }}</h3>
        <br>
        <img src="{{ item.image.url }}">
    </div>
</a>

sectionranks/templates/sectionranks/includes_unlocked_kits.html
{% load static %}
<div class="section-item-3" align="center">
    <h3 class="section-item-name">{{ item.name }}</h3>
    <br>
    <img src="{{ item.image.url }}">
</div>

sectionranks/templates/sectionranks/includes_unlocked_paints.html
{% load static %}
<a class="section-item-2" href="/paints/{{ item.slug_name }}">
    <div align="center">
        <h3 class="section-item-name">{{ item.name }}</h3>
        <br>
        <img src="{{ item.image_icon.url }}">
    </div>
</a>

sectionranks/templates/sectionranks/ranks_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ rank.rank_name }}{% endblock %}

{% block add_css %}<link rel="stylesheet" type="text/css" href="{% static 'sectionranks/css/ranks-detail_style.css' %}">
<style>
body {
    background-image: url({% static 'main/img/tanki_bg.jpg' %});
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
}
</style>{% endblock %}

{% block content %}
<div class="bodywrap">
    {% include "main/includes_header.html" %}
    <main>
        <h1 id="title">{{ rank.rank_name }}</h1>

        <div class="menu">
            <a href="{% url 'ranks-main' %}"><div class="button-back">Вернуться к разделу <b>Звания</b></div></a>

            <hr>
            <h2 class="text_section">Информация о звании</h2>
            <hr>
            <br>

            <div class="flex-section">
                {% if prev_rank is not Null %}
                <a href="{% url 'ranks-detail' r=prev_rank.slug_name %}" class="item-link">
                    <div class="section-item" align="center">
                        <p class="text-description">Предыдущее звание:</p>
                        <img src="{{ prev_rank.rank_icon.url }}" title="{{ prev_rank.rank_name }}">
                    </div>
                </a>
                {% else %}
                <div class="section-item" align="center">
                    <p class="text-description">Предыдущее звание:</p>
                    <p class="text-description"><i>Нет</i></p>
                </div>
                {% endif %}

                <div class="section-inner-wrapper" align="center">
                    <div align="center">
                        <p class="text-description">№{{ rank.id }}) <b>{{ rank.rank_name }}</b></p>
                        <img src="{{ rank.rank_icon.url }}">
                    </div>
                    <div>
                        <p class="text-description"><b>Опыт:</b> {{ rank.exp_start }}</p>
                        <p class="text-description"><b>До следующего звания:</b> +{{ rank.exp_next }}</p>
                        <p class="text-description"><b>Награда:</b> {{ rank.cry_bonus }} <img src="{% static 'main/img/small_icons/cry.png' %}" title="Кристаллов"></p>
                    </div>
                </div>

                {% if next_rank is not Null %}
                <a href="{% url 'ranks-detail' r=next_rank.slug_name %}" class="item-link">
                    <div class="section-item" align="center">
                        <p class="text-description">Следующее звание:</p>
                        <img src="{{ next_rank.rank_icon.url }}" title="{{ next_rank.rank_name }}">
                    </div>
                </a>
                {% else %}
                <div class="section-item" align="center">
                    <p class="text-description">Следующее звание:</p>
                    <p class="text-description"><i>Нет</i></p>
                </div>
                {% endif %}
            </div>

            <br>
            <hr>
            <h2 class="text_section">Доступно на этом звании</h2>
            <hr>
            <br>

            <hr>
            <h6 class="section-item-name">Пушки</h6>
            <hr>
            <div class="flex-section-2">
                {% for item in rank.smoki_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.firebird_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.twins_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.railgun_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.hammer_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.isida_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.vulcan_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.freeze_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.thunder_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.ricochet_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}

                {% for item in rank.shaft_set.all %}
                {% include 'sectionranks/includes_unlocked_cannons.html' %}
                {% endfor %}
            </div>
            <hr>

            <h6 class="section-item-name">Корпуса</h6>
            <hr>
            <div class="flex-section-2">
                {% for item in rank.hunter_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}

                {% for item in rank.vasp_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}

                {% for item in rank.titan_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}

                {% for item in rank.dictator_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}

                {% for item in rank.hornet_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}

                {% for item in rank.mammoth_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}

                {% for item in rank.viking_set.all %}
                {% include 'sectionranks/includes_unlocked_hulls.html' %}
                {% endfor %}
            </div>
            <hr>

            <h6 class="section-item-name">Краски</h6>
            <hr>
            <div class="flex-section-2">
                {% for item in rank.paint_set.all %}
                {% include 'sectionranks/includes_unlocked_paints.html' %}
                {% endfor %}
            </div>
            <hr>

            <h6 class="section-item-name">Комплекты</h6>
            <hr>
            <div class="flex-section-2">
                {% for item in arm_kits %}
                {% include 'sectionranks/includes_unlocked_kits.html' %}
                {% endfor %}

                {% for item in supply_kits %}
                {% include 'sectionranks/includes_unlocked_kits.html' %}
                {% endfor %}

                {% for item in kits %}
                {% include 'sectionranks/includes_unlocked_kits.html' %}
                {% endfor %}
            </div>
            <hr>

        </div>
    </main>
</div>
{% include "main/includes_footer.html" %}
{% endblock %}

sectionranks/templates/sectionranks/ranks_main.html
{% extends "base.html" %}
{% load static %}

{% block title %}Звания{% endblock %}

{% block add_css %}<link rel="stylesheet" type="text/css" href="{% static 'sectionranks/css/ranks-main_style.css' %}">
<style>
body {
    background-image: url({% static 'main/img/tanki_bg.jpg' %});
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
}
</style>{% endblock %}

{% block content %}
<div class="bodywrap">
    {% include "main/includes_header.html" %}
    <main>
        <h1 id="title">Звания</h1>

        <div class="menu">

            <a href="/"><div class="button-back">Вернуться на главную</div></a>

            <p class="text">
                Звания — это способ показать и сравнить заработанный в танковых баталиях опыт игроков. Названия и значки званий в «ProTanki» созданы на основе реально существующих воинских званий.
            </p>
            <p class="text">
                В игре есть 30 званий, список которых представлен ниже. Крушите вражеские танки, продвигайтесь вверх по карьерной лестнице званий и открывайте для себя новое вооружение, ведь плох тот Новобранец, который не мечтает стать Генералиссимусом!
            </p>

            <hr>
            <h2 class="text_section">Способы получения новых званий</h2>
            <hr>

            <p class="text">
                Текущий прогресс игрока можно отследить при помощи его звания. Для того чтобы получить следующие звание, нужно заработать определённое количество <b>очков опыта</b>.
            </p>
            <p class="text">
                Их можно получить следующими способами:
            </p>
            <ul class="text">
                <li>Уничтожение противников;</li>
                <li>Помощь в уничтожении противников;</li>
                <li>Лечение союзников Изидой;</li>
                <li>Манипуляции с флагами в CTF и ASL (доставка флага, взятие и перенос флага, уничтожение вражеского флагоносца, возврат флага);</li>
                <li>Манипуляции с точками в CP (захват точки, перезахват точки);</li>
                <li>Покупка в гараже абонемента «1000 опыта»;</li>
                <li>Покупка премиум аккаунта, с ним можно получать на 50% очков опыта больше за каждое вышеперечисленное действие.</li>
            </ul>

            <hr>
            <h2 class="text_section">Список званий</h2>
            <hr>

            <p class="text">
                Новые звания открывают доступ к новому вооружению и новым возможностям игры. Кроме того, за получение нового звания игроки награждаются определённой суммой кристаллов, а на начальных званиях и припасами.
            </p>

            <div class="flex-section">
                {% for rank in rank_list %}
                <a class="section-item" href="{% url 'ranks-detail' r=rank.slug_name %}">
                    <h6 class="section-item-name">{{ rank.rank_name }}</h6>
                    <div align="center">
                        <img src="{{ rank.rank_icon.url }}">
                    </div>
                    <hr>
                    <p class="section-item-text"><b>Опыт: </b>{{ rank.exp_start }}</p>
                    <hr>
                    <p class="section-item-text"><b>До след. звания: </b>+{{ rank.exp_next }}</p>
                    <hr>
                    <p class="section-item-text"><b>Награда: </b>{{ rank.cry_bonus }} <img src="{% static 'main/img/small_icons/cry.png' %}" title="Кристаллов"></p>
                </a>

                {% endfor %}
            </div>

        </div>
    </main>
</div>
{% include "main/includes_footer.html" %}
{% endblock %}

sectionranks/templates/sectionranks/ranks_no_such_rank.html
{% extends "base.html" %}
{% load static %}

{% block title %}Не найдено звание{% endblock %}

{% block add_css %}<link rel="stylesheet" type="text/css" href="{% static 'sectionranks/css/ranks-detail_style.css' %}">
<style>
body {
    background-image: url({% static 'main/img/tanki_bg.jpg' %});
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
}
</style>{% endblock %}

{% block content %}
<div class="bodywrap">
    {% include "main/includes_header.html" %}
    <main>
        <h1 id="title">Не найдено звание</h1>

        <div class="menu">
            <a href="{% url 'ranks-main' %}"><div class="button-back">Вернуться к разделу <b>Звания</b></div></a>

            <p class="text">Звание по url-запросу "{{ rank }}" не найдено.</p>
        </div>
    </main>
</div>
{% include "main/includes_footer.html" %}
{% endblock %}